config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :cars
  resources :bookings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car_id, only: %i[show edit update destroy]
  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.save
    redirect_to car_path(@car)
  end

  def edit
  end

  def update
    @car.update(car_params)
    redirect_to car_path(@car)
  end

  def destroy
    @car.destroy
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :km, :year, :options, :color, :price, :photo)
  end

  def set_car_id
    @car = Car.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/cars/_form.erb
<div class="container mt-5 mx-auto">
  <%= simple_form_for(@car) do |f| %>
    <%= f.input :photo, as: :file %>
    <%= f.input :brand %>
    <%= f.input :model %>
    <%= f.input  :km %>
    <%= f.input  :year %>
    <%= f.input :options %>
    <%= f.input  :color %>
    <%= f.input  :price %>
     <div  class="mx-auto">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/cars/edit.html.erb
<h1 class="text-center">Cars#edit</h1>

<%= render 'form', car: @car %>
<%= link_to "Nos voitures", cars_path %>

app/views/cars/index.html.erb
<div class="container my-5">
  <%= image_tag  ("https://res.cloudinary.com/drip4exjp/image/upload/v1668193315/peugeot_rjk54m.jpg"), class: "img-fluid rounded-5" %>
</div>

<div class="container my-5 d-flex justify-content-start flex-column">
  <h1 class="h1 text-start ">Nos voitures</h1>
  <hr style="width: 100px; color: red; margin-right: 15px; margin-top: 5px;"  >
</div>

<div class="container p-3 my-5 shadow rounded-5" style="background-color: whitesmoke;">
  <div class="d-flex justify-content-around flex-wrap p-5">
    <% @cars.each do |car| %>
      <%= link_to car_path(car)  , class:"mcard shadow rounded-5" do   %>
        <%= car.brand.capitalize %> <%= car.model.capitalize %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<h1 class="text-center">Cars</h1>

<%= render 'form', car: @car %>
<p class="text-center"><%= link_to "Nos voitures", cars_path %></p>

app/views/cars/show.html.erb
<div class="container my-5">
  <%=  cl_image_tag @car.photo.key, height: 900, width: 1440, crop: :fill, class:"img-fluid shadow-lg  rounded-5"%>
</div>

<div class="container">
    <h1 class="h1 text-danger text-start my-5"><%= @car.brand.capitalize %> <%= @car.model.capitalize %></h1>
      <ul class="list-group my-5 text-center" style="border-radius:10px">
        <li class="list-group-item bg-dark text-white">Km: <%= @car.km %></li>
        <li class="list-group-item bg-light">Année: <%= @car.year %></li>
        <li class="list-group-item bg-dark text-white"> Transmission: <%= @car.options %></li>
        <li class="list-group-item bg-light">Couleur: <%= @car.color %></li>
        <li class="list-group-item bg-dark text-white">Prix: <%= @car.price %>€/jour</li>
      </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carlocation</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
  <%= yield %>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container my-5 img-fluid rounded-5 banner"
  style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
  url(https://res.cloudinary.com/drip4exjp/image/upload/v1667778883/development/julian-hochgesang-AetmDwMVzio-unsplash_hvd7bz.jpg);">
  <div class="container text-center text-white">
    <h1 class="h1">MADA CAR</h1>
    <p>Location de voitures entre particuliers en Martinique !</p>
    <%= link_to "Nos voitures", cars_path, class: "btn btn-secondary  text-white col-lg-2 mx-auto" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
     Mada Car - <i class="fas fa-heart"></i> - Location de Voiture en Martinique
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon shadow-sm">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>